version: '2.1'
services:
  eureka:
    restart: always
    ports:
      - 8002:8002

  config:
    restart: always
    ports:
      - 8001:8001

  gateway:
    restart: always
    ports:
      - 9632:9632
  file:
    restart: always
    ports:
      - 6004:6004
      - 3306:3306
  product:
    restart: always
    ports:
      - 6007:6007
  promotion:
    restart: always
    ports:
      - 6005:6005
  send:
    restart: always
    ports:
      - 6003:6003
  user:
    restart: always
    ports:
      - 6006:6006
  workflow:
    restart: always
    ports:
      - 6008:6008