
server:
  port: 8002

spring:
  application:
    name: own-eureka



management:
  context-path: /eureka

logging:
  level: debug
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000


security:
  basic:
    enabled: true
  user:
    name: own
    password: own-microserver


