server:
  port: 8001

spring:
  application:
    name: own-config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Blucezhang/center-config
          search-paths: application*,own*
          #native:
            #search-locations:
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone:  http://own:123456@localhost:8002/eureka

---
spring:
  profiles: test
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://own:123456@eureka:8002/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://own:123456@eureka:8002/eureka
