
server:
  port: 8001





spring:
  application:
    name: own-config
  profiles:
    active:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Blucezhang/center-config.git


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone:









management:
  context-path: /config


logging:
  level: debug

